# Assignment For Numpy

## Diffculty Level : Beginner

### 1. Import the numpy package under the name np

In [1]:
import numpy as np

### 2. Create a null vector of size 10

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 3. Create a vector with values ranging from 10 to 49

In [7]:
y = np.arange(10,49)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[0 2 4 6 8]
(5,)


### 4. Find the shape of previous array in question 3

In [4]:
print(y.shape) # return / count of no. elements in array 'y'

(39,)


### 5. Print the type of the previous array in question 3

In [8]:
print(type(y))

<class 'numpy.ndarray'>


### 6. Print the numpy version and the configuration

In [9]:
print("NumPy Version")
print(np.__version__)
print("==============")
print("NumPy Configuration")
print(np.show_config())


NumPy Version
1.18.1
NumPy Configuration
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/hp/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_

### 7. Print the dimension of the array in question 3

In [10]:
print(y.ndim)

1


### 8. Create a boolean array with all the True values

In [12]:
np.ones((2,2),dtype=bool)

array([[ True,  True],
       [ True,  True]])

### 9. Create a two dimensional array

In [20]:
arr3 = np.arange(30).reshape(5,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### 10. Create a three dimensional array

In [26]:
arr4 = np.arange(40).reshape(2,4,5) 
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

## Diffculty Level : Easy

### 1. Reverse a vector (first element becomes last)

In [3]:
a = np.arange(10,20)
print("Orignal Array")
print("=============")
print(a)
print("Reverse Array")
print("=============")
a = a[::-1]
print(a)

Orignal Array
[10 11 12 13 14 15 16 17 18 19]
Reverse Array
[19 18 17 16 15 14 13 12 11 10]


### 2. Create a null vector of size 10 but the fifth value which is 1

In [4]:
arr5 = np.zeros(10)
arr5[4] = 1
arr5

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 3. Create a 3x3 identity matrix

In [5]:
arr6 = np.identity(3)
print("3 * 3 Matrix")
print("============")
print(arr6)

3 * 3 Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### arr = np.array([1, 2, 3, 4, 5])

### 4. Convert the data type of the given array from int to float

In [6]:
newarr = np.array([1,2,3,4,5],dtype='float')
newarr

array([1., 2., 3., 4., 5.])

### arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

### 5. Multiply arr1 with arr2

In [164]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]]) 

newarr2 = arr1 * arr2

newarr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

### arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

### 6. Make an array by comparing both the arrays provided above

In [7]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

comparison = arr1 == arr2
arr_comp = comparison.all()
print(arr_comp)

False


### 7. Extract all odd numbers from arr with values(0-9)

In [107]:
newarr4 = np.arange(10)

print("Original Array")
print("==============")
print(newarr4)

result = [] #create a empty list

for i in newarr4:
    if i % 2 != 0:
        result.append(i)

print("Odd Numbers from array")
print("======================")
print(np.array(result)) # convert list to array    
        

Original Array
[0 1 2 3 4 5 6 7 8 9]
Odd Numbers from array
[1 3 5 7 9]


### 8. Replace all odd numbers to -1 from previous array

In [124]:
a = np.array(result)
a[a%2==1] = -1
print(a)

[-1 -1 -1 -1 -1]


### arr = np.arange(10)

### 9. Replace the values of indexes 5,6,7 and 8 to 12

In [163]:
arr = np.arange(10)

print(arr)

arr[arr[arr > 5]-1] = 12
print('\n')
print(arr)

[0 1 2 3 4 5 6 7 8 9]


[ 0  1  2  3  4 12 12 12 12  9]


### 10. Create a 2d array with 1 on the border and 0 inside

In [143]:
newarr7 = np.ones((5,5))

print("Original Array")
print("==============")
print(newarr7)

print("1 on the border and 0 inside in the array")

newarr7[1:-1,1:-1] = 0

print(newarr7)


Original Array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Difficulty Level Medium

### arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

### 1. Replace the value 5 to 12

In [5]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

### arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

### 2. Convert all the values of 1st array to 64

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[0][0] = 64

arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### 3. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [147]:
arr2d = np.arange(10).reshape(2,5)
print("Original Array")
print("==============")
print(arr2d)


print("After Slicing")
print("==============")
x , y = arr2d[0,1:], arr2d[-1:]

print(x)
print(y)

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]
After Slicing
[1 2 3 4]
[[5 6 7 8 9]]


### 4. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [165]:
arr2d = np.arange(10).reshape(2,5)
print("Original Array")
print("==============")
print(arr2d)

print("After Slicing")
print("==============")

x, y = arr2d[1,0:], arr2d[:-1]

print(x)
print('\n')
print(y)

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]
After Slicing
[5 6 7 8 9]


[[0 1 2 3 4]]


### 5. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [331]:
arr2d = np.arange(10).reshape(2,5)
print("Original Array")
print("==============")
print(arr2d)

#arr2d[:,0:-2:1]
#arr2d[0][1]

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]


### 6. Create a 10x10 array with random values and find the minimum and maximum values

In [322]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.96608113 0.96692652 0.02939447 0.21435051 0.70601558 0.82014074
  0.21305886 0.43833942 0.55622593 0.3330844 ]
 [0.21541226 0.8586661  0.78458799 0.03790905 0.25719013 0.95623285
  0.2464853  0.35724922 0.79983298 0.2900749 ]
 [0.10264806 0.7981456  0.16007462 0.37038831 0.40009633 0.64017062
  0.2789812  0.07821657 0.84351719 0.78309221]
 [0.07723865 0.91050643 0.04214479 0.40118671 0.76208664 0.56732607
  0.99835225 0.93811654 0.82490494 0.29104695]
 [0.42576524 0.09037018 0.24107618 0.76561994 0.79852741 0.93376408
  0.61590372 0.95896936 0.47923866 0.05861868]
 [0.8141475  0.76391961 0.68298908 0.5859401  0.698005   0.74212266
  0.73892733 0.70352918 0.87103702 0.44299619]
 [0.58122571 0.59799177 0.95038813 0.44966765 0.89567282 0.80813042
  0.51420982 0.02907638 0.68761899 0.29139096]
 [0.67053066 0.94115059 0.72775179 0.54622161 0.50311533 0.47286522
  0.42839753 0.7939595  0.96527331 0.34024336]
 [0.11301445 0.35593732 0.18509561 0.8623919  0.16117026 0.62966

### a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

### 7. Find the common items between a and b

In [325]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

print("Array # 1 : ",a)
print("Array # 2 : ",b)

# use the np.intersect1d method
c = np.intersect1d(a,b)

print("Common Values : ",c)

Array # 1 :  [1 2 3 2 3 4 3 4 5 6]
Array # 2 :  [ 7  2 10  2  7  4  9  4  9  8]
Common Values :  [2 4]


### a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

### 8. Find the positions where elements of a and b match

In [328]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

### 9. Find all the values from array data where the values from array names are not equal to Will

In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.array(np.random.randn(7, 4)*10,dtype='int')

print("names : ",names)
print("data : ",data)

data[names != 'Will']

names :  ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data :  [[-12  -5  -7  14]
 [ -3  10   0  11]
 [ -3   6   3  -1]
 [ 13 -12   1   1]
 [-14 -15  -1   3]
 [ -6  -4 -17  -7]
 [ -8   0  -5  14]]


array([[-12,  -5,  -7,  14],
       [ -3,  10,   0,  11],
       [ 13, -12,   1,   1],
       [ -6,  -4, -17,  -7],
       [ -8,   0,  -5,  14]])

### names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

### 10. Find all the values from array data where the values from array names are not equal to Will and Joe

In [21]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.array(np.random.randn(7, 4)*10,dtype='int')

print("names : ",names)
print("data : ",data)

mask = (names != 'Will') & (names != 'Joe')

data[mask]

names :  ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data :  [[  4   6  -4  10]
 [  7  -2   6   7]
 [  7 -12   2   5]
 [ -5  21  -4   9]
 [-12  -6   7  -5]
 [-22  -3   7  -2]
 [  0   3  -6 -10]]


array([[ 4,  6, -4, 10],
       [-5, 21, -4,  9]])

## Difficulty Level Hard

### 1. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15

In [38]:
newarr = np.array(np.arange(1,16).reshape(5,3),dtype='float')

newarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

### 2. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [39]:
newarr1 = np.array(np.arange(1,17).reshape(2,2,4),dtype='float')

newarr1

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

### 3. Swap axes of the array you created in Question 32 (previous question)

In [46]:
print("Original Array")
print("=============")
print(newarr1)
print ('\n')
print("After applying swap axes")
print("========================")
print (np.swapaxes(newarr1,0,2))

Original Array
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


After applying swap axes
[[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]


### 4. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [64]:
x = np.arange(10).reshape(2,5)
print("Original Array")
print("==============")
print(x)
print('\n')

y = np.sqrt(x).reshape(2,5)
print("Square root of every element")
print("============================")
print(y)
print('\n')

print("After Apply where")
print("=================")
z = np.array(np.where(y<0.5,0,y)).reshape(2,5)
print(z)

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]


Square root of every element
[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


After Apply where
[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


### 5. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [76]:
random1 = np.random.randn(12)

print("Random Array # 1")
print(random1)

print('\n')

random2 = np.random.randn(12)

print("Random Array # 2")
print(random2)

print('\n')

newrandom = np.maximum(random1,random2)
5
print("Maximum Values between each element of the two array")
print(newrandom)

Random Array # 1
[ 0.84628578  2.11321878  0.65468047 -1.34531255 -0.43965269 -1.01368737
 -0.42686052  1.93498687  1.20027536  1.11953118  0.23296182  1.17626809]


Random Array # 2
[-1.16672473  0.4165175  -0.69222933 -1.27447093  0.19911865 -0.81807163
  1.78953125 -2.08866981 -1.2724833   0.31526328 -0.31409408  0.95495304]


Maximum Values between each element of the two array
[ 0.84628578  2.11321878  0.65468047 -1.27447093  0.19911865 -0.81807163
  1.78953125  1.93498687  1.20027536  1.11953118  0.23296182  1.17626809]


### names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

### 6. Find the unique names and sort them out!

In [82]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

print("Original Array")
print("===============")
print(names)
print('\n')
unique = np.unique(names)

unames = np.asarray((unique)).T
print("Unique Values")
print("=============")

print(unames)

Original Array
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


Unique Values
['Bob' 'Joe' 'Will']


### a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

### 7. From array a remove all items present in array b

In [88]:
a = np.array([1,2,3,4,5])
print(a)
print('\n')
b = np.array([5,6,7,8,9])
print(b)
print('\n')
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4 5]


[5 6 7 8 9]


[1 2 3 4]


### 8. Following is the input NumPy array. delete column two and insert following new column in its place.

### sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

### newColumn = numpy.array([[10,10,10]])

In [100]:
import numpy as numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print("Original Array")
print(sampleArray)
print('\n')
newColumn = numpy.array([[10,10,10]])
print("New Column")
print(newColumn)
print('\n')

sampleArray = numpy.delete(sampleArray,1,1)

print("After delete column two from original")
print(sampleArray)
print('\n')

sampleArray = np.insert(sampleArray,1,newColumn,axis=1)
print("Adding new column")
print("=================")
print(sampleArray)


Original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]


New Column
[[10 10 10]]


After delete column two from original
[[34 73]
 [82 12]
 [53 66]]


Adding new column
[[34 10 73]
 [82 10 12]
 [53 10 66]]


### x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

### 9. Find the dot product of the above two matrix

In [103]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print(x)
print('\n')
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(y)
print('\n')
z = np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]


[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


[[ 28.  64.]
 [ 67. 181.]]


### 10. Generate a matrix of 20 random values and find its cumulative sum

In [106]:
a = np.random.randn(20)

print("Original Array")
print(a)
print('\n')

print("Cumulative Sum")
b = np.cumsum(a)
print(b)

Original Array
[-2.10607859 -0.12207874 -0.80525947  0.27703221  0.18480991 -1.21908795
  0.47489114  1.93206902 -0.72183078  1.37579469 -0.42505892  1.01496325
  1.10939428 -0.2643432  -0.01166653  0.79925343  0.68329467 -0.88992613
 -0.1558779   0.8772235 ]


Cumulative Sum
[-2.10607859 -2.22815732 -3.03341679 -2.75638458 -2.57157467 -3.79066262
 -3.31577148 -1.38370246 -2.10553324 -0.72973855 -1.15479748 -0.13983423
  0.96956005  0.70521685  0.69355032  1.49280375  2.17609842  1.28617229
  1.13029438  2.00751788]
