# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output:: 

#### array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [6]:
import numpy as np

x = np.arange(10).reshape((-1,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

### How to stack two arrays vertically?

#### Desired Output::

#### array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [14]:
import numpy as np
a = np.arange(10).reshape(2,5)
b = np.ones(10).reshape(2,5)

c = np.array(np.vstack((a,b)),dtype='int')

c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

#### array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
import numpy as np
a = np.arange(10).reshape(2,5)
b = np.ones(10).reshape(2,5)

c = np.array(np.hstack((a,b)),dtype='int')

c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to Convert higher dimension into one dimension?

#### Desired Output::

#### array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]) 

In [22]:
import numpy as np

x = np.arange(15).reshape(1,3,5)
y = np.array(x.flatten())
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

#### array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]]) 

In [23]:
import numpy as np

arr = np.arange(15).reshape((-1,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [26]:
import numpy as np

arr = np.arange(25).reshape(5,5)
print("Original Array")
print("==============")
print(arr)
newarr = np.array(np.square(arr))
print("Square of an Array")
print("==================")
print(newarr)

Original Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Square of an Array
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [33]:
import numpy as np

x = np.arange(30).reshape(5,6)
print("Original Array")
print("==============")
print(x)
y = np.mean(x)
print("Mean of array")
print("=============")
print(y)

Original Array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean of array
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [34]:
import numpy as np

x = np.arange(30).reshape(5,6)
print("Array of Question:8")
print("===================")
print(x)
y = np.std(x)
print("Mean of Array")
print("=============")
print(y)

Array of Question:8
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean of Array
8.65544144839919


## Question:11

### Find the transpose of the previous array in Q8?

In [35]:
import numpy as np

x = np.arange(30).reshape(5,6)
print("Array of Question:8")
print("===================")
print(x)
y = np.transpose(x)
print("Transpose of Array")
print("==================")
print(y)

Array of Question:8
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Transpose of Array
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [37]:
import numpy as np

arr = np.arange(16).reshape(4,4)
print("Original Array")
print("==============")
print(arr)
newarr = np.trace(arr)
print("Sum of diagonal elements")
print("========================")
print(newarr)

Original Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of diagonal elements
30


## Question:13

### Find the determinant of the previous array in Q12?

In [38]:
import numpy as np

arr = np.arange(16).reshape(4,4)
print("Array of Question:12")
print("====================")
print(arr)
newarr = np.linalg.det(arr)
print("Determinant of array")
print("====================")
print(newarr)

Array of Question:12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Determinant of array
0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [49]:
import numpy as np

x = np.arange(100).reshape(4,25)
print("Original Array : \n",x)
y = np.percentile(x,5)
print("5th Percentile of an array : ",y)
z = np.percentile(x,95)
print("95th Percentile of an array :",z)

Original Array : 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]
5th Percentile of an array :  4.95
95th Percentile of an array : 94.05


## Question:15

### How to find if a given array has any null values?

In [52]:
import numpy as np

a = [[1,2,3,4,5],[6,7,8,9,0]]
b = [[2,4,6,8,10],[np.nan,3,np.nan,7,np.nan]]
c = np.array(np.isnan(a))
print(c)
print('\n')
d = np.array(np.isnan(b))
print(d)

[[False False False False False]
 [False False False False False]]


[[False False False False False]
 [ True False  True False  True]]
